# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
#Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

[project]
name = "csaf-20-to-21-converter-test-tools"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
  # needed for prototype_runtests.py
  "jsonpath-rfc9535>=1.0.0",
  # needed for visualizer.py
  "markdown",
  "mdx_truly_sane_lists"
]

# we do not really want to build and distribute something for this repo
# (but still declare dependencies in a most useful way for automation,
#  in a way that does not introduce further dependencies)
# so we use pip as it is in python and comes with python itself
# and until https://github.com/pypa/pip/issues/11440 (Add --only-deps [..])
# is solved, we disable the discovery for the build step
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = []
